backend:
  name: git-gateway
  branch: main # หากแป้นหลักบน GitHub ชื่อ master ให้เปลี่ยนเป็น master

collections:
  - name: "queue_management"
    label: "ระบบจัดการคิว"
    files:
      - file: "data/queues.yml"
        label: "รายการคิวทั้งหมด"
        name: "queues"
        fields:
          - label: "รายการคิว"
            name: "queues"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "เลขคิว", name: "queueNumber", widget: "string" }
              - { label: "ชื่อลูกค้า", name: "customerName", widget: "string" }
              - { label: "ความคืบหน้า (%)", name: "progress", widget: "number", value_type: "int", min: 0, max: 100 }
              - { label: "วันที่", name: "date", widget: "string" }
